# Generated by Django 2.2.5 on 2019-09-14 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tracks',
            new_name='Track',
        ),
    ]
